# -*- coding: utf-8 -*-
"""spotify personal analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-GVimPdyn6-nd0ACIAbOaGO9DXNAl35
"""

from google.colab import files
uploaded = files.upload()  # selecione o novo .zip (o Extended, de 12MB)

import zipfile

with zipfile.ZipFile(list(uploaded.keys())[0], 'r') as zip_ref:
    zip_ref.extractall('spotify_extended')

import os

for root, dirs, files in os.walk('spotify_extended'):
    for f in files:
        print(os.path.join(root, f))

import pandas as pd
import glob
import json

arquivos = glob.glob('spotify_extended/**/Streaming_History_Audio_*.json', recursive=True)
print(f"{len(arquivos)} arquivos encontrados")

dfs = []
for arquivo in arquivos:
    with open(arquivo, 'r', encoding='utf-8') as f:
        dados = json.load(f)
        dfs.append(pd.DataFrame(dados))

df = pd.concat(dfs, ignore_index=True)
print(df.shape)
df.head()

# Converter timestamp
df['ts'] = pd.to_datetime(df['ts'])

# Converter ms tocados em minutos
df['min_played'] = df['ms_played'] / 60000

# Selecionar colunas mais úteis
df = df[['ts', 'master_metadata_track_name', 'master_metadata_album_artist_name',
         'master_metadata_album_album_name', 'min_played', 'ms_played',
         'reason_end', 'skipped', 'shuffle']]

df.rename(columns={
    'master_metadata_track_name': 'faixa',
    'master_metadata_album_artist_name': 'artista',
    'master_metadata_album_album_name': 'album'
}, inplace=True)

# Remover linhas sem faixa (podcasts, por exemplo)
df = df.dropna(subset=['faixa'])

# Colunas auxiliares de tempo
df['ano'] = df['ts'].dt.year
df['mes'] = df['ts'].dt.month
df['dia_semana'] = df['ts'].dt.day_name()
df['hora'] = df['ts'].dt.hour

print(f"Total de horas escutadas: {df['min_played'].sum()/60:.1f}h")
df.head()

import plotly.express as px

por_ano = df.groupby('ano')['min_played'].sum().reset_index()
por_ano['horas'] = por_ano['min_played'] / 60

fig = px.pie(por_ano, values='min_played', names='ano',
             title='Distribuição de Minutos Escutados por Ano',
             hover_data=['horas'])
fig.update_traces(textinfo='percent+label')
fig.show()

"""Transformação desses dados em .csv

"""

df.to_csv('spotify_tratado.csv', index=False, encoding='utf-8-sig')

from google.colab import files
files.download('spotify_tratado.csv')  # ou 'spotify_tratado.xlsx'