# -*- coding: utf-8 -*-
"""spotify personal analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-GVimPdyn6-nd0ACIAbOaGO9DXNAl35
"""

from google.colab import files
uploaded = files.upload()  # selecione o .zip que o Spotify te enviou

import zipfile

with zipfile.ZipFile(list(uploaded.keys())[0], 'r') as zip_ref:
    zip_ref.extractall('spotify_data')

import pandas as pd
import glob
import json

arquivos = glob.glob('spotify_data/**/StreamingHistory_music_*.json', recursive=True)
print(f"{len(arquivos)} arquivos encontrados")

dfs = []
for arquivo in arquivos:
    with open(arquivo, 'r', encoding='utf-8') as f:
        dados = json.load(f)
        dfs.append(pd.DataFrame(dados))

df = pd.concat(dfs, ignore_index=True)
print(df.shape)
df.head()

# Converter endTime pra datetime
df['ts'] = pd.to_datetime(df['endTime'])

# ms tocados em minutos
df['min_played'] = df['msPlayed'] / 60000

df.rename(columns={
    'trackName': 'faixa',
    'artistName': 'artista'
}, inplace=True)

df = df[['ts', 'faixa', 'artista', 'min_played', 'msPlayed']]
df = df.dropna(subset=['faixa'])

# Colunas auxiliares de tempo
df['ano'] = df['ts'].dt.year
df['mes'] = df['ts'].dt.month
df['dia_semana'] = df['ts'].dt.day_name()
df['hora'] = df['ts'].dt.hour

print(f"Total de horas escutadas: {df['min_played'].sum()/60:.1f}h")
df.head()